### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by dmkov2016** [DualH/cordova-plugin-installreferrer#1]
Hi! Would you please explain where to put "import { InstallReferrer } from 'install-referrer';" and other code? 
If I use something like "market://details?id=com.myname.here&ref_id=614", how can I get this "614"?

**Comment by DualH** [comment]
Hello @dmkov2016, sorry for the delay.

Well, for Ionic 3 the way to use this plugin is this:

Because @ionic-native doesn't have install-referrer, you must copy the folder from my npm and paste in node_modules/@ionic-native

```js
// In your app.module.ts
import { InstallReferrer } from '@ionic-native/install-referrer';

...

providers: [
    ...
    InstallReferrer,
    ...
  ]
```

Then go to your app.component.ts and add

```js
// In your app.component.ts

import { InstallReferrer } from '@ionic-native/install-referrer';

@Component({
  ...
  providers: [ InstallReferrer ]
})

constructor(
  ...
  private installReferrer: InstallReferrer)
{
  let params;
  this.platform.ready()
    .then(() => {
      this.installReferrer.getReferrer()
      .then(data => {
        params = data['ref_id'];
      })
      .catch(err => {
        // Proccess your error
      });
    })
}
```

For anything contact me.

Regards.

**Comment by DualH** [comment]
@dmkov2016 [UPDATE]

Use this link to create the link for catch it in the app

https://developers.google.com/analytics/devguides/collection/android/v4/campaigns?hl=es-419
